### PR TITLE
Update $message value for translation

### PR DESCRIPTION
**Pull request by Tungenius**
Update the difference between Insee.php and validators.fr.xlf

### CODE REVIEW

**Comment by sstok** [comment]
You need to update the tests 👍

**Comment by Soullivaneuh** [comment]
Thank for your contribution  @Tungenius 

Could you please fix Travis?

**Comment by Soullivaneuh** [comment]
Thank you @Tungenius! :+1:

**Comment by Soullivaneuh** [comment]
Released here: https://github.com/Soullivaneuh/IsoCodesValidator/releases/tag/v3.1.2

**Pull request merged**
